### ISSUE TITLE
Rambo FMVs weirdness

### ISSUE THREAD

**Issue by SeongGino** [lindbergh-loader/lindbergh-loader#14]
As part of my testing games on an Arch-based system (as followed in #6), I did manage to get Rambo working.

Seems though that the FMVs behave strangely, and presumably it's because this is one of the few games that inter-splices pre-rendered videos in the middle of gameplay (I'm just making an assumption here).

The attract video seems to work fine, as does the intro sequence to the first stage - but the intermissions mid-stage (after the first half of the trench sequence, mid-stage-boss battle and post-boss victory result) only show the first frame of the video; subtitles will still appear/disappear as they're meant to (image 1).

![2024_01-26 202130-Rambo](https://github.com/bobbydilley/lindbergh-loader/assets/7321839/7ab707ef-fd0f-449b-8776-90a74aae1678)
![2024_01-26 202431-Rambo](https://github.com/bobbydilley/lindbergh-loader/assets/7321839/a1a8d52a-f7e9-4949-9971-c9713000c05e)

After finishing the first stage boss, after the victory video screen appears, the following FMV stalls along with the audio entirely, then the game crashes.

[Full startup log here.](https://github.com/bobbydilley/lindbergh-loader/files/14070563/ramboStdout.txt)
As mentioned, may have to do with #6 again (me using Arch when lindbergh-loader is built for Ubuntu LTS 22) so I'll have to reinvestigate this with an Ubuntu setup/distrobox setup at a later point. Thought it should be noted regardless.

**Comment by SeongGino** [comment]
I was able to test in a Distrobox instance of Ubuntu 22.04, and the behavior is a bit different. The midgame FMVs that froze on the Arch host did play in Ubuntu, but at a far too fast framerate--eventually leading to the pre-boss-finisher video playing, then crashing before it could return to gameplay.

**Comment by bobbydilley** [comment]
Please try again with new release, and create a new issue if the problem isn't fixed!
