### ISSUE TITLE
X Error of failed request:  BadValue (integer parameter out of range for operation)

### ISSUE THREAD

**Issue by Keeboy99** [lindbergh-loader/lindbergh-loader#18]
Running Ubuntu 22.04 and getting the following error

keeboy@DESKTOP:~/hotd4/elf$ ./lindbergh
$ ./hod4M.elf
ERROR: ld.so: object 'lindbergh.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

SEGA Lindbergh Emulator
Robert Dilley 2023

  GAME:       The House of the Dead 4 Rev A
  GAME ID:    SBLC
  DVP:        DVP-0003A
  STATUS:     WORKING
Warning: Skipping SEGFAULT 3A
Connecting to 116.109.112.47
Connecting to 109.112.47.46
  RESOLUTION: 640x480

X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  149 (XFree86-VidModeExtension)
  Minor opcode of failed request:  12 (XF86VidModeSetViewPort)
  Value in failed request:  0x600003
  Serial number of failed request:  49
  Current serial number in output stream:  50

**Comment by Keeboy99** [comment]
[lindbergh.txt](https://github.com/user-attachments/files/15833636/lindbergh.txt)
my conf renamed to .txt so I can upload

**Comment by bobbydilley** [comment]
Please try again with new release, and create a new issue if the problem isn't fixed!

Make sure that if you're using a laptop your AMD or NVIDIA card is set to the primary card.
